-- V1 initial schema (translated from EF Core migrations)

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  email varchar(256) NOT NULL UNIQUE,
  password varchar(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_records (
  id text PRIMARY KEY,
  uid text NOT NULL,
  product_id text NOT NULL,
  quantity integer NOT NULL,
  product_json clob NOT NULL
);

CREATE TABLE IF NOT EXISTS order_records (
  id uuid PRIMARY KEY,
  uid text NOT NULL,
  items_json clob NOT NULL,
  amount numeric NOT NULL,
  status text NOT NULL,
  payment_status text NOT NULL,
  payment_method text,
  coupon_code text,
  payment_reference_id text,
  seller_ids_json clob NOT NULL,
  address_json clob NOT NULL,
  created_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY,
  name varchar(200) NOT NULL,
  price numeric NOT NULL,
  quantity integer NOT NULL,
  category varchar(100) NOT NULL,
  description varchar(2000) NOT NULL,
  image_url varchar(1000) NOT NULL,
  seller_id varchar(100) NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profiles (
  uid text PRIMARY KEY,
  email varchar(256) NOT NULL,
  role varchar(32) NOT NULL,
  wallet_balance numeric NOT NULL,
  display_name varchar(200),
  phone varchar(32),
  photo_url varchar(1000),
  password_hash varchar(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS wishlist_records (
  id text PRIMARY KEY,
  uid text NOT NULL,
  product_id text NOT NULL,
  product_json clob NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_records (
  id text PRIMARY KEY,
  order_id text NOT NULL,
  uid text,
  payment_method text,
  status text NOT NULL,
  reference_id text,
  created_at bigint NOT NULL
);
