-- V5 create any backend tables missing from older local PostgreSQL databases.

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  email varchar(256) NOT NULL UNIQUE,
  password varchar(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY,
  name varchar(200) NOT NULL,
  price numeric NOT NULL,
  quantity integer NOT NULL,
  category varchar(100) NOT NULL,
  description varchar(2000) NOT NULL,
  image_url varchar(1000) NOT NULL,
  seller_id varchar(100) NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_records (
  id text PRIMARY KEY,
  order_id text NOT NULL,
  uid text,
  payment_method text,
  status text NOT NULL,
  reference_id text,
  created_at bigint NOT NULL
);
