server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    # default: in-memory for quick dev
    url: jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: verysecretkeyforsamples_only_change
    expiration-ms: 3600000

logging:
  level:
    org.hibernate.SQL: DEBUG

---
# Production profile (Postgres)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

